import { Config } from 'tailwindcss';
import plugin = require('tailwindcss/plugin');

export const tailwindConfiguration = {
  content: [],
  plugins: [
    plugin(function ({ addBase }) {
      addBase({
        ':root': {
          '--lgc-screen-xs': '320px',
          '--lgc-screen-sm': '576px',
          '--lgc-screen-md': '768px',
          '--lgc-screen-lg': '992px',
          '--lgc-screen-xl': '1200px',
          '--space-0': '0px',
          '--space-50': '0.25rem',
          '--space-100': '0.5rem',
          '--space-150': '0.75rem',
          '--space-200': '1rem',
          '--space-250': '1.25rem',
          '--space-300': '1.5rem',
          '--space-400': '2rem',
          '--space-500': '2.5rem',
          '--space-600': '3rem',
          '--space-800': '4rem',
          '--space-1000': '5rem',
          '--space-xxs': 'var(--space-50)',
          '--space-xs': 'var(--space-100)',
          '--space-sm': 'var(--space-150)',
          '--space-md': 'var(--space-200)',
          '--space-lg': 'var(--space-200)',
          '--space-xl': 'var(--space-250)',
          '--space-2xl': 'var(--space-300)',
          '--space-3xl': 'var(--space-400)',
          '--space-4xl': 'var(--space-500)',
          '--space-5xl': 'var(--space-600)',
          '--space-6xl': 'var(--space-800)',
          '--radius-0': '0rem',
          '--radius-50': '0.25rem',
          '--radius-100': '0.5rem',
          '--radius-150': '0.75rem',
          '--radius-200': '1rem',
          '--radius-250': '1.25rem',
          '--radius-300': '1.5rem',
          '--radius-xs': 'var(--radius-50)',
          '--radius-sm': 'var(--radius-100)',
          '--radius-md': 'var(--radius-150)',
          '--radius-lg': 'var(--radius-200)',
          '--radius-xl': 'var(--radius-250)',
          '--radius-full': '9999rem',
          '--shadow-xs': '0px 1px 4px 0px rgba(95, 109, 179, 0.24)',
          '--shadow-sm': '0px 1px 8px 0px rgba(95, 109, 179, 0.24)',
          '--shadow-md': '0px 2px 12px 0px rgba(95, 109, 179, 0.24)',
          '--shadow-lg': '0px 4px 16px 0px rgba(95, 109, 179, 0.24)',
          '--shadow-xl': '0px 8px 24px 0px rgba(95, 109, 179, 0.24)',
          '--shadow-2xl': '0px 12px 32px 0px rgba(95, 109, 179, 0.24)',
          '--shadow-form': '0px -2px 0px 0px #dbDFE4 inset',
          '--shadow-form-hover': '0px -2px 0px 0px #bec6d4 inset',
          '--shadow-form-active': '0px -2px 0px 0px #00b1c2 inset',
          '--shadow-form-error': '0px -2px 0px 0px #ce365a inset',
          '--shadow-focus': '0px 0px 0px 3px rgba(0, 177, 194,0.24)',
          '--font-size-150': '0.75rem',
          '--font-size-175': '0.875rem',
          '--font-size-200': '1rem',
          '--font-size-250': '1.25rem',
          '--font-size-300': '1.5rem',
          '--font-size-350': '1.75rem',
          '--font-size-450': '2.25rem',
          '--font-size-550': '2.75rem',
          '--line-height-150': '0.75rem',
          '--line-height-175': '0.875rem',
          '--line-height-200': '1rem',
          '--line-height-250': '1.25rem',
          '--line-height-300': '1.5rem',
          '--line-height-350': '1.75rem',
          '--line-height-400': '2rem',
          '--line-height-450': '2.25rem',
          '--line-height-550': '2.75rem',
          '--line-height-650': '3.25rem',
          '--font-size-heading-2xl': 'var(--font-size-350)',
          '--font-size-heading-xl': 'var(--font-size-350)',
          '--font-size-heading-lg': 'var(--font-size-300)',
          '--font-size-heading-md': 'var(--font-size-250)',
          '--font-size-heading-sm': 'var(--font-size-200)',
          '--font-size-heading-xs': 'var(--font-size-175)',
          '--font-size-body-lead': 'var(--font-size-250)',
          '--font-size-body-md': 'var(--font-size-200)',
          '--font-size-body-sm': 'var(--font-size-175)',
          '--font-size-body-xs': 'var(--font-size-150)',
          '--font-size-form-md': 'var(--font-size-200)',
          '--font-size-form-sm': 'var(--font-size-175)',
          '--font-size-form-xs': 'var(--font-size-150)',
          '--line-height-heading-2xl': 'var(--line-height-450)',
          '--line-height-heading-xl': 'var(--line-height-450)',
          '--line-height-heading-lg': 'var(--line-height-400)',
          '--line-height-heading-md': 'var(--line-height-350)',
          '--line-height-heading-sm': 'var(--line-height-300)',
          '--line-height-heading-xs': 'var(--line-height-250)',
          '--line-height-body-lead': 'var(--line-height-350)',
          '--line-height-body-md': 'var(--line-height-300)',
          '--line-height-body-sm': 'var(--line-height-250)',
          '--line-height-body-xs': 'var(--line-height-200)',
          '--line-height-form-md': 'var(--line-height-300)',
          '--line-height-form-sm': 'var(--line-height-200)',
          '--line-height-form-xs': 'var(--line-height-175)',
        },
      });
      addBase({
        //medium screen
        '@media (min-width:768px) and (max-width: 992px)': {
          ':root': {
            '--font-size-heading-2xl': 'var(--font-size-450)',
            '--font-size-heading-xl': 'var(--font-size-350)',
            '--line-height-heading-2xl': 'var(--line-height-550)',
            '--line-height-heading-xl': 'var(--line-height-450)',
          },
        },
        '@media (min-width:992px)': {
          // large screens
          ':root': {
            '--space-xxs': 'var(--space-50)',
            '--space-xs': 'var(--space-100)',
            '--space-sm': 'var(--space-150)',
            '--space-md': 'var(--space-200)',
            '--space-lg': 'var(--space-250)',
            '--space-xl': 'var(--space-300)',
            '--space-2xl': 'var(--space-400)',
            '--space-3xl': 'var(--space-500)',
            '--space-4xl': 'var(--space-600)',
            '--space-5xl': 'var(--space-800)',
            '--space-6xl': 'var(--space-1000)',
            '--radius-md': 'var(--radius-200)',
            '--radius-lg': 'var(--radius-250)',
            '--radius-xl': 'var(--radius-300)',
            '--font-size-heading-2xl': 'var(--font-size-550)',
            '--font-size-heading-xl': 'var(--font-size-450)',
            '--font-size-heading-lg': 'var(--font-size-350)',
            '--font-size-heading-md': 'var(--font-size-300)',
            '--font-size-heading-sm': 'var(--font-size-250)',
            '--font-size-heading-xs': 'var(--font-size-200)',
            '--line-height-heading-2xl': 'var(--line-height-650)',
            '--line-height-heading-xl': 'var(--line-height-550)',
            '--line-height-heading-lg': 'var(--line-height-450)',
            '--line-height-heading-md': 'var(--line-height-400)',
            '--line-height-heading-sm': 'var(--line-height-350)',
            '--line-height-heading-xs': 'var(--line-height-300)',
          },
        },
      });
    }),
  ],
  theme: {
    fontSize: {
      'heading-2xl': [
        'var(--font-size-heading-2xl)',
        { lineHeight: 'var(--line-height-heading-2xl)' },
      ],
      'heading-xl': [
        'var(--font-size-heading-xl)',
        { lineHeight: 'var(--line-height-heading-xl)' },
      ],
      'heading-lg': [
        'var(--font-size-heading-lg)',
        { lineHeight: 'var(--line-height-heading-lg)' },
      ],
      'heading-md': [
        'var(--font-size-heading-md)',
        { lineHeight: 'var(--line-height-heading-md)' },
      ],
      'heading-sm': [
        'var(--font-size-heading-sm)',
        { lineHeight: 'var(--line-height-heading-sm)' },
      ],
      'heading-xs': [
        'var(--font-size-heading-xs)',
        { lineHeight: 'var(--line-height-heading-xs)' },
      ],
      'body-lead': [
        'var(--font-size-body-lead)',
        { lineHeight: 'var(--line-height-body-lead)' },
      ],
      'body-md': [
        'var(--font-size-body-md)',
        { lineHeight: 'var(--line-height-body-md)' },
      ],
      'body-sm': [
        'var(--font-size-body-sm)',
        { lineHeight: 'var(--line-height-body-sm)' },
      ],
      'body-xs': [
        'var(--font-size-body-xs)',
        { lineHeight: 'var(--line-height-body-xs)' },
      ],
      'form-md': [
        'var(--font-size-form-md)',
        { lineHeight: 'var(--line-height-form-md)' },
      ],
      'form-sm': [
        'var(--font-size-form-sm)',
        { lineHeight: 'var(--line-height-form-sm)' },
      ],
      'form-xs': [
        'var(--font-size-form-xs)',
        { lineHeight: 'var(--line-height-form-xs)' },
      ],
      '150': 'var(--font-size-150)',
      '175': 'var(--font-size-175)',
      '200': 'var(--font-size-200)',
      '250': 'var(--font-size-250)',
      '300': 'var(--font-size-300)',
      '350': 'var(--font-size-350)',
      '450': 'var(--font-size-450)',
      '550': 'var(--font-size-550)',
    },
    lineHeight: {
      '150': 'var(--line-height-150)',
      '175': 'var(--line-height-175)',
      '200': 'var(--line-height-200)',
      '250': 'var(--line-height-250)',
      '300': 'var(--line-height-300)',
      '350': 'var(--line-height-350)',
      '400': 'var(--line-height-400)',
      '450': 'var(--line-height-450)',
      '550': 'var(--line-height-550)',
      '650': 'var(--line-height-650)',
    },
    spacing: {
      '0': 'var(--space-0)',
      '50': 'var(--space-50)',
      '100': 'var(--space-100)',
      '150': 'var(--space-150)',
      '200': 'var(--space-200)',
      '250': 'var(--space-250)',
      '300': 'var(--space-300)',
      '400': 'var(--space-400)',
      '500': 'var(--space-500)',
      '600': 'var(--space-600)',
      '800': 'var(--space-800)',
      '1000': 'var(--space-1000)',
      xxs: 'var(--space-xxs)',
      xs: 'var(--space-xs)',
      sm: 'var(--space-sm)',
      md: 'var(--space-md)',
      lg: 'var(--space-lg)',
      xl: 'var(--space-xl)',
      '2xl': 'var(--space-2xl)',
      '3xl': 'var(--space-3xl)',
      '4xl': 'var(--space-4xl)',
      '5xl': 'var(--space-5xl)',
      '6xl': 'var(--space-6xl)',
    },
    space: {
      '0': 'var(--space-0)',
      '50': 'var(--space-50)',
      '100': 'var(--space-100)',
      '150': 'var(--space-150)',
      '200': 'var(--space-200)',
      '250': 'var(--space-250)',
      '300': 'var(--space-300)',
      '400': 'var(--space-400)',
      '500': 'var(--space-500)',
      '600': 'var(--space-600)',
      '800': 'var(--space-800)',
      '1000': 'var(--space-1000)',
      xxs: 'var(--space-xxs)',
      xs: 'var(--space-xs)',
      sm: 'var(--space-sm)',
      md: 'var(--space-md)',
      lg: 'var(--space-lg)',
      xl: 'var(--space-xl)',
      '2xl': 'var(--space-2xl)',
      '3xl': 'var(--space-3xl)',
      '4xl': 'var(--space-4xl)',
      '5xl': 'var(--space-5xl)',
      '6xl': 'var(--space-6xl)',
    },
    borderRadius: {
      0: 'var(--radius-0)',
      50: 'var(--radius-50)',
      100: 'var(--radius-100)',
      150: 'var(--radius-150)',
      200: 'var(--radius-200)',
      250: 'var(--radius-250)',
      300: 'var(--radius-300)',
      xs: 'var(--radius-xs)',
      sm: 'var(--radius-sm)',
      md: 'var(--radius-md)',
      lg: 'var(--radius-lg)',
      xl: 'var(--radius-xl)',
      full: 'var(--radius-full)',
    },
    boxShadow: {
      none: 'none',
      xs: 'var(--shadow-xs)',
      sm: 'var(--shadow-sm)',
      md: 'var(--shadow-md)',
      lg: 'var(--shadow-lg)',
      xl: 'var(--shadow-xl)',
      '2xl': 'var(--shadow-2xl)',
      form: 'var(--shadow-form)',
      'form-hover': 'var(--shadow-form-hover)',
      'form-active': 'var(--shadow-form-active)',
      'form-error': 'var(--shadow-form-error)',
      focus: 'var(--shadow-focus)',
    },
    screens: {
      xs: 'var(--lgc-screen-xs, 320px)',
      sm: 'var(--lgc-screen-sm, 576px)',
      md: 'var(--lgc-screen-md, 768px)',
      lg: 'var(--lgc-screen-lg, 992px)',
      xl: 'var(--lgc-screen-xl, 1200px)',
    },
    extend: {},
  },
} as Config;
